///////////////////////////////////////////////////////////
//  Administrador.cs
//  Implementation of the Class Administrador
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:21:53 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using Changarro.Model;
using Changarro.Model.DTO;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace ChangarroBusiness
{
    public class Administrador {

        CHANGARROEntities db = new CHANGARROEntities();

        public Administrador(){

        }

        public AdministradorDTO ObtenerAdministrador(int iIdAdministrador)
        {
            AdministradorDTO _oAdministrador = new AdministradorDTO();

            using (CHANGARROEntities ctx = new CHANGARROEntities())
            {
                _oAdministrador = ctx.tblCat_Administrador.AsNoTracking()
                    .Where(c => c.iIdAdministrador == iIdAdministrador)
                    .Select(o => new AdministradorDTO
                    {
                        cNombre = o.cNombre,
                        cApellido = o.cApellido,
                        cTelefono = o.cTelefono,
                        cCorreo = o.cCorreo

                    }).FirstOrDefault();
            }
            return _oAdministrador;
        }

        public AdministradorDTO ObtenerDatosAdministrador(int iIdAdministrador)
        {
            AdministradorDTO _oAdministrador = new AdministradorDTO();

            using (CHANGARROEntities ctx = new CHANGARROEntities())
            {
                _oAdministrador = ctx.tblCat_Administrador.AsNoTracking()
                    .Where(c => c.iIdAdministrador == iIdAdministrador)
                    .Select(o => new AdministradorDTO
                    {
                        cNombre = o.cNombre,
                        cApellido = o.cApellido,
                        cTelefono = o.cTelefono,
                        cCorreo = o.cCorreo

                    }).FirstOrDefault();
            }
            return _oAdministrador;
        }

        public AdministradorDTO EditarDatos(AdministradorDTO oAdministrador)
        {
            using (CHANGARROEntities ctx = new CHANGARROEntities())
            {
                ctx.Configuration.LazyLoadingEnabled = false;
                ctx.Configuration.ProxyCreationEnabled = false;

                tblCat_Administrador _oAdministrador = ctx.tblCat_Administrador.FirstOrDefault(c => c.iIdAdministrador == oAdministrador.iIdAdministrador); //consulta para obtener al cliente

                _oAdministrador.cNombre = oAdministrador.cNombre;
                _oAdministrador.cApellido = oAdministrador.cApellido;
                _oAdministrador.cTelefono = oAdministrador.cTelefono;
                _oAdministrador.cCorreo = oAdministrador.cCorreo;

                ctx.Entry(oAdministrador).State = EntityState.Modified;
                ctx.SaveChanges();
            }

            return oAdministrador;
        }

        public tblCat_Administrador ObtenerDatos(int iIdCliente)
        {
            tblCat_Administrador oAdministrador = db.tblCat_Administrador.AsNoTracking().FirstOrDefault(c => c.iIdAdministrador == iIdAdministrador);
            return oAdministrador;
        }

    }//end Administrador

}//end namespace ChangarroBusiness