///////////////////////////////////////////////////////////
//  Administrador.cs
//  Implementation of the Class Administrador
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:21:53 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using Changarro.Model.DTO;

namespace ChangarroBusiness
{
    public class Administrador {

		public Administrador(){

		}

		~Administrador(){

		}

		public AdministradorDTO EditarDatos(){

			return null;
		}

		/// 
		/// <param name="iIdAdministrador"></param>
		public AdministradorDTO ObtenerDatos(int iIdAdministrador){

			return null;
		}

	}//end Administrador

}//end namespace ChangarroBusiness