///////////////////////////////////////////////////////////
//  Carrito.cs
//  Implementation of the Class Carrito
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:15:04 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Changarro.Model;

namespace ChangarroBusiness {
	public class Carrito {

		public Carrito(){

		}

		~Carrito(){

		}

		/// 
		/// <param name="iIdProducto"></param>
		public void AgregarAcarrito(int iIdProducto){

		}

		/// 
		/// <param name="iIdCarritoProducto"></param>
		public void EliminarProducto(int iIdCarritoProducto){

		}

		/// 
		/// <param name="iIdCliente"></param>
		public List<tbl_DetalleCarrito> ObtenerCarrito(int iIdCliente){

			return null;
		}

		/// 
		/// <param name="iIdCliente"></param>
		public void VaciarCarrito(int iIdCliente){

		}

	}//end Carrito

}//end namespace ChangarroBusiness