///////////////////////////////////////////////////////////
//  Categoria.cs
//  Implementation of the Class Categoria
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:22:49 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroBusiness {
	public class Categoria {

		public Categoria(){

		}

		~Categoria(){

		}

		public CategoriaDTO AgregarCategoria(){

			return null;
		}

		/// 
		/// <param name="iIdCategoria"></param>
		public void DesactivarCategoria(int iIdCategoria){

		}

		/// 
		/// <param name="iIdCategoria"></param>
		public CategoriaDTO EditarCategoria(int iIdCategoria){

			return null;
		}

		public List<tblCategoria> ObtenerCategorias(){

			return null;
		}

		public List<ProductoDTO> ObtenerProductos(){

			return null;
		}

	}//end Categoria

}//end namespace ChangarroBusiness