///////////////////////////////////////////////////////////
//  Cliente.cs
//  Implementation of the Class Cliente
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:14:48 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ChangarroBusiness;
namespace ChangarroBusiness {
	public class Cliente {

		public ChangarroBusiness.Direccion m_Direccion;

		public Cliente(){

		}

		~Cliente(){

		}

		public ClienteDTO AgregarCliente(){

			return null;
		}

		/// 
		/// <param name="iIdCliente"></param>
		public bool DesactivarCliente(int iIdCliente){

			return false;
		}

		/// 
		/// <param name="iIdCliente"></param>
		public ClienteDTO EditarDatos(int iIdCliente){

			return null;
		}

		public List<ClienteAdministradorDTO> ObtenerClientes(){

			return null;
		}

		/// 
		/// <param name="iIdCliente"></param>
		public ClienteDTO ObtenerDatos(int iIdCliente){

			return null;
		}

		public List<ClienteAdministradorDTO> ObtenerTopClientes(){

			return null;
		}

		public ClienteDTO ValidarCliente(){

			return false;
		}

	}//end Cliente

}//end namespace ChangarroBusiness