///////////////////////////////////////////////////////////
//  Compra.cs
//  Implementation of the Class Compra
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:15:32 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroBusiness {
	public class Compra {

		public Compra(){

		}

		~Compra(){

		}

		/// 
		/// <param name="iIdCompra"></param>
		public void CancelarCompra(int iIdCompra){

		}

		/// 
		/// <param name="iIdCliente"></param>
		public List<CompraDTO> ObtenerCompras(int iIdCliente){

			return null;
		}

		/// 
		/// <param name="iIdProducto"></param>
		/// <param name="iCantidad"></param>
		public void RealizarCompra(int iIdProducto, int iCantidad){

		}

		/// 
		/// <param name="iIdCarrito"></param>
		public void RealizarCompraCarrito(int iIdCarrito){

		}

	}//end Compra

}//end namespace ChangarroBusiness