///////////////////////////////////////////////////////////
//  Domicilio.cs
//  Implementation of the Class Domicilio
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:15:16 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
using Changarro.Model;
using Changarro.Model.DTO;

namespace Changarro.Business
{
    public class Domicilio {

        CHANGARROEntities db;
		public Domicilio(){
            db = new CHANGARROEntities();
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
		}

		~Domicilio(){

		}

		public DomicilioDTO AgregarDomicilio(){

			return null;
		}

		/// 
		/// <param name="iIdDomicilio"></param>
		public void DesactivarDomicilio(int iIdDomicilio){

		}

		/// 
		/// <param name="iIdDomicilio"></param>
		public DomicilioDTO EditarDomicilio(int iIdDomicilio){

			return null;
		}

		/// 
		/// <param name="iIdCliente"></param>
		public List<DomicilioDTO> ObtenerDomicilios(int iIdCliente){

			return null;
		}

        public List<DomicilioCompraDTO> ObtenerDomiciliosCompra(int iIdCliente)
        {
            List<DomicilioCompraDTO> _lstDomicilios = db.tblCat_Direccion.AsNoTracking().Where(d => d.iIdCliente == iIdCliente && d.lEstatus == true).Select(d => new DomicilioCompraDTO
            {
                iIdDomicilio = d.iIdDireccion,
                cNombre = d.cNombre,
                cDomicilio = d.cCalle + " " + d.cNumeroExterior + " " + d.cColonia + ", " + d.cMunicipio + ", " + d.tbl_Estado.cNombre
            }).ToList();

            return _lstDomicilios;
        }

		public bool ValidarDomicilio(){

			return false;
		}

	}//end Domicilio

}//end namespace ChangarroBusiness