///////////////////////////////////////////////////////////
//  Domicilio.cs
//  Implementation of the Class Domicilio
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:15:16 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroBusiness {
	public class Domicilio {

		public Domicilio(){

		}

		~Domicilio(){

		}

		public DomicilioDTO AgregarDomicilio(){

			return null;
		}

		/// 
		/// <param name="iIdDomicilio"></param>
		public void DesactivarDomicilio(int iIdDomicilio){

		}

		/// 
		/// <param name="iIdDomicilio"></param>
		public DomicilioDTO EditarDomicilio(int iIdDomicilio){

			return null;
		}

		/// 
		/// <param name="iIdCliente"></param>
		public List<DomicilioDTO> ObtenerDomicilios(int iIdCliente){

			return null;
		}

		public bool ValidarDomicilio(){

			return false;
		}

	}//end Domicilio

}//end namespace ChangarroBusiness