///////////////////////////////////////////////////////////
//  Productos.cs
//  Implementation of the Class Productos
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:22:17 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroBusiness {
	public class Productos {

		public Productos(){

		}

		~Productos(){

		}

		public ProductoDTO AgregarProducto(){

			return null;
		}

		/// 
		/// <param name="iIdProducto"></param>
		public void DesactivarProducto(int iIdProducto){

		}

		/// 
		/// <param name="iIdProducto"></param>
		public ProductoDTO EditarProducto(int iIdProducto){

			return null;
		}

		public List<ProductoDTO> ObtenerProductos(){

			return null;
		}

		public List<ProductoDTO> ObtenerTopProductos(){

			return null;
		}

	}//end Productos

}//end namespace ChangarroBusiness