///////////////////////////////////////////////////////////
//  Productos.CHANGARROEntitiescs
//  Implementation of the Class Productos
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:22:17 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using Changarro.Model;
using Changarro.Model.DTO;
using System.Linq;
using System.Data.Entity;
using System;

namespace Changarro.Business
{

    public class Productos
    {
        private readonly CHANGARROEntities db;

        public Productos()
        {
            db = new CHANGARROEntities();
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
        }


        ~Productos()
        {

        }

        public ProductosDTO AgregarProducto(tblCat_Producto _objProducto)
        {
            DbContextTransaction dbTran = db.Database.BeginTransaction();//investigar 
            try
            {
                db.tblCat_Producto.Add(_objProducto);

                db.SaveChanges();
                dbTran.Commit();
            }
            catch (Exception)
            {
                dbTran.Rollback();
                throw;
            }


            return null;
        }

        /// 
        /// <param name="iIdProducto"></param>
        public void DesactivarProducto(int iIdProducto)
        {

        }

        /// 
        /// <param name="iIdProducto"></param>
        public ProductosDTO EditarProducto(int iIdProducto)
        {

            return null;
        }

        public List<ProductosDTO> ObtenerProductos()
        {

            return null;
        }

        public List<ProductosDTO> ObtenerTopProductos()
        {

            return null;
        }
        /// <summary>
        /// Trae los datos de la tabla de productos
        /// </summary>
        /// <returns></returns>
        public List<ListaProductosDTO> ObtenerListaProductos()
        {
            List<ListaProductosDTO> lstProducto = (from producto in db.tblCat_Producto
                                                   join cat in db.tblCat_Categoria
                                                   on producto.iIdCategoria equals cat.iIdCategoria
                                                   select new ListaProductosDTO
                                                   {
                                                       iIdProducto = producto.iIdProducto,
                                                       cNombre = producto.cNombre,
                                                       NombreCate = cat.cNombre,
                                                       iCantidad = producto.iCantidad,
                                                       dtFechaAlta = producto.dtFechaAlta,
                                                       dtFechaModificacion = producto.dtFechaModificacion

                                                   }).ToList();

            return lstProducto;
        }
        /// <summary>
        /// Obtiene los datos de un producto de acuerdo a si ID
        /// </summary>
        /// <param name="_iIdProducto"></param>
        /// <returns></returns>
        public tblCat_Producto ObtenerProducto(int _iIdProducto)
        {
            tblCat_Producto oProducto = db.tblCat_Producto.Where(p => p.iIdProducto == _iIdProducto).FirstOrDefault();
            return oProducto;
        }
        /// <summary>
        /// Obtiene una lista de los 6 productos mas recientes que han sido agregados a la BD.
        /// </summary>
        /// <returns>Regresa la lista de los 6 productos</returns>
        public List<CatalogoProductosDTO> ObtenerProductosRecientes()
        {
            List<CatalogoProductosDTO> _lstProductos = db.tblCat_Producto.AsNoTracking().Select(p => new CatalogoProductosDTO()
            {
                iIdProducto = p.iIdProducto,
                iIdCategoria = p.iIdCategoria,
                dPrecio = p.dPrecio,
                cNombre = p.cNombre,
                cImagen = p.cImagen,
                dtFechaAlta = (DateTime)p.dtFechaAlta
            }).OrderByDescending(p => p.dtFechaAlta).Take(6).ToList();
            return _lstProductos;

        }

        /// <summary>
        /// Este método obtiene los productos relacionados a la categoría seleccionada.
        /// </summary>
        /// <param name="iIdCategoria">La id de la categoría seleccionada.</param>
        /// <returns>Regresa un listado de los productos relacionados.</returns>
        public List<CatalogoProductosDTO> ObtenerProductosPorCategoria(int iIdCategoria)
        {
            List<CatalogoProductosDTO> _lstProductos = db.tblCat_Producto.AsNoTracking().Select(p => new CatalogoProductosDTO()
            {
                iIdProducto = p.iIdProducto,
                iIdCategoria = p.iIdCategoria,
                dPrecio = p.dPrecio,
                cNombre = p.cNombre,
                cImagen = p.cImagen,
                dtFechaAlta = (DateTime)p.dtFechaAlta
            }).Where(p => p.iIdCategoria == iIdCategoria).ToList();

            return _lstProductos;
        }

        public List<CatalogoProductosDTO> ObtenerProductosPorBusqueda(string cBusqueda)
        {
            List<CatalogoProductosDTO> _lstProductos = db.tblCat_Producto.AsNoTracking().Select(p => new CatalogoProductosDTO()
            {
                iIdProducto = p.iIdProducto,
                iIdCategoria = p.iIdCategoria,
                dPrecio = p.dPrecio,
                cNombre = p.cNombre,
                cImagen = p.cImagen,
                dtFechaAlta = (DateTime)p.dtFechaAlta
            }).Where(p => p.cNombre.Contains(cBusqueda)).ToList();

            return _lstProductos;
        }

        /// <summary>
        /// Obtiene un objeto del producto seleccionado para ver detalles.
        /// </summary>
        /// <param name="iIdProducto">La id del producto seleccionado.</param>
        /// <returns>Regresa el objeto encontrado con la id.</returns>
        public DetallesProductoDTO ObtenerDetallesProducto(int iIdProducto)
        {
            DetallesProductoDTO _oProducto = db.tblCat_Producto.AsNoTracking().Select(p => new DetallesProductoDTO()
            {
                iIdProducto = p.iIdProducto,
                iIdCategoria = p.iIdCategoria,
                iCantidad = p.iCantidad,
                dPrecio = p.dPrecio,
                cNombre = p.cNombre,
                cImagen = p.cImagen,
                cDescripcion = p.cDescripcion
            }).FirstOrDefault(p => p.iIdProducto == iIdProducto);

            return _oProducto;
        }
    }//end Productos

}//end namespace ChangarroBusiness