///////////////////////////////////////////////////////////
//  Tarjeta.cs
//  Implementation of the Class Tarjeta
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:14:39 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
using Changarro.Model;
using Changarro.Model.DTO;

namespace Changarro.Business
{
    public class Tarjeta {
        CHANGARROEntities db;

		public Tarjeta(){
            db = new CHANGARROEntities();
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
		}

		~Tarjeta(){

		}

		public TarjetaDTO AgregarTarjeta(){

			return null;
		}

		/// 
		/// <param name="iIdTarjeta"></param>
		public void DesactivarTarjeta(int iIdTarjeta){

		}

		/// 
		/// <param name="iIdCliente"></param>
		public List<TarjetaDTO> ObtenerTarjetas(int iIdCliente){

			return null;
		}

		public bool ValidarTarjeta(){

			return false;
		}


        public List<TarjetaCompraDTO> ObtenerTarjetasCompra(int iIdCliente)
        {
            List<TarjetaCompraDTO> _lstTarjetas = db.tblCat_Tarjeta.AsNoTracking().Where(t => t.iIdCliente == iIdCliente && t.lEstatus == true).Select(t => new TarjetaCompraDTO
            {
                iIdTarjeta = t.iIdTarjeta,
                cNombre = t.cNombre,
                cTarjeta = t.cNumeroTarjeta.Substring(t.cNumeroTarjeta.Length - 4)
            }).ToList();

            return _lstTarjetas;
        }
	}//end Tarjeta

}//end namespace ChangarroBusiness