///////////////////////////////////////////////////////////
//  Tarjeta.cs
//  Implementation of the Class Tarjeta
//  Generated by Enterprise Architect
//  Created on:      14-nov.-2019 05:14:39 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroBusiness {
	public class Tarjeta {

		public Tarjeta(){

		}

		~Tarjeta(){

		}

		public TarjetaDTO AgregarTarjeta(){

			return null;
		}

		/// 
		/// <param name="iIdTarjeta"></param>
		public void DesactivarTarjeta(int iIdTarjeta){

		}

		/// 
		/// <param name="iIdCliente"></param>
		public List<TarjetasDTO> ObtenerTarjetas(int iIdCliente){

			return null;
		}

		public bool ValidarTarjeta(){

			return false;
		}

	}//end Tarjeta

}//end namespace ChangarroBusiness