//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHANGARROEntities : DbContext
    {
        public CHANGARROEntities()
            : base("name=CHANGARROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DetalleCarrito> tbl_DetalleCarrito { get; set; }
        public virtual DbSet<tbl_DetalleCompra> tbl_DetalleCompra { get; set; }
        public virtual DbSet<tbl_Estado> tbl_Estado { get; set; }
        public virtual DbSet<tblCat_Administrador> tblCat_Administrador { get; set; }
        public virtual DbSet<tblCat_Carrito> tblCat_Carrito { get; set; }
        public virtual DbSet<tblCat_Categoria> tblCat_Categoria { get; set; }
        public virtual DbSet<tblCat_Cliente> tblCat_Cliente { get; set; }
        public virtual DbSet<tblCat_Compra> tblCat_Compra { get; set; }
        public virtual DbSet<tblCat_Direccion> tblCat_Direccion { get; set; }
        public virtual DbSet<tblCat_Producto> tblCat_Producto { get; set; }
        public virtual DbSet<tblCat_Tarjeta> tblCat_Tarjeta { get; set; }
    }
}
