//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DetalleCarrito
    {
        public int iIdDetalleCarrito { get; set; }
        public int iIdCarrito { get; set; }
        public int iIdProducto { get; set; }
        public decimal iCantidad { get; set; }
    
        public virtual tblCat_Carrito tblCat_Carrito { get; set; }
        public virtual tblCat_Producto tblCat_Producto { get; set; }
    }
}
