//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DetalleCompra
    {
        public int iIdDetalleCompra { get; set; }
        public int iIdCompra { get; set; }
        public int iIdProducto { get; set; }
        public int iCantidad { get; set; }
    
        public virtual tblCat_Compra tblCat_Compra { get; set; }
        public virtual tblCat_Producto tblCat_Producto { get; set; }
    }
}
