//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DetalleCompra
    {
        public int iIdDetalleCompra { get; set; }
        public int iIdCompra { get; set; }
        public int iIdProducto { get; set; }
        public int iCantidad { get; set; }
    
        public virtual tblCat_Compra tblCat_Compra { get; set; }
        public virtual tblCat_Producto tblCat_Producto { get; set; }
    }
}
