//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat_Cliente()
        {
            this.tblCat_Carrito = new HashSet<tblCat_Carrito>();
            this.tblCat_Compra = new HashSet<tblCat_Compra>();
            this.tblCat_Direccion = new HashSet<tblCat_Direccion>();
            this.tblCat_Tarjeta = new HashSet<tblCat_Tarjeta>();
        }
    
        public int iIdCliente { get; set; }
        public string cNombre { get; set; }
        public string cApellido { get; set; }
        public string cTelefono { get; set; }
        public string cCorreo { get; set; }
        public string cContrasenia { get; set; }
        public string cImagen { get; set; }
        public bool lEstatus { get; set; }
        public Nullable<System.DateTime> dtFechaAlta { get; set; }
        public Nullable<System.DateTime> dtFechaBaja { get; set; }
        public Nullable<System.DateTime> dtFechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_Carrito> tblCat_Carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_Compra> tblCat_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_Direccion> tblCat_Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_Tarjeta> tblCat_Tarjeta { get; set; }
    }
}
