//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Administrador
    {
        public int iIdAdministrador { get; set; }
        public string cNombre { get; set; }
        public string cApellido { get; set; }
        public string cTelefono { get; set; }
        public string cCorreo { get; set; }
        public string cContrasenia { get; set; }
        public string cImagen { get; set; }
    }
}
