//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Administrador
    {
        public int iIdAdministrador { get; set; }
        public string cNombre { get; set; }
        public string cApellido { get; set; }
        public string cTelefono { get; set; }
        public string cCorreo { get; set; }
        public string cContrasenia { get; set; }
        public string cImagen { get; set; }
    }
}
