//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat_Direccion()
        {
            this.tblCat_Compra = new HashSet<tblCat_Compra>();
        }
    
        public int iIdDireccion { get; set; }
        public int iIdCliente { get; set; }
        public int iIdEstado { get; set; }
        public int iCodigoPostal { get; set; }
        public string cNombre { get; set; }
        public string cCalle { get; set; }
        public string cNumeroExterior { get; set; }
        public string cNumeroInterior { get; set; }
        public string cColonia { get; set; }
        public string cMunicipio { get; set; }
        public string cDescripcion { get; set; }
        public bool lEstatus { get; set; }
    
        public virtual tbl_Estado tbl_Estado { get; set; }
        public virtual tblCat_Cliente tblCat_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_Compra> tblCat_Compra { get; set; }
    }
}
