//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Changarro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat_Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat_Tarjeta()
        {
            this.tblCat_Compra = new HashSet<tblCat_Compra>();
        }
    
        public int iIdTarjeta { get; set; }
        public int iIdCliente { get; set; }
        public string cNombre { get; set; }
        public string cTitular { get; set; }
        public string cNumeroTarjeta { get; set; }
        public bool lEstatus { get; set; }
        public System.DateTime dtMesExpiracion { get; set; }
        public System.DateTime dtAnioExpiracion { get; set; }
    
        public virtual tblCat_Cliente tblCat_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCat_Compra> tblCat_Compra { get; set; }
    }
}
