///////////////////////////////////////////////////////////
//  CarritoDTO.cs
//  Implementation of the Class CarritoDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:41 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroDTO {
	public class CarritoDTO {

		public CarritoDTO(){

		}

		~CarritoDTO(){

		}

		public int cDescripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

		public int cNombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

		public int iCantidad{
			get{
				return iCantidad;
			}
			set{
				iCantidad = value;
			}
		}

		public int iIdProducto{
			get{
				return iIdProducto;
			}
			set{
				iIdProducto = value;
			}
		}

	}//end CarritoDTO

}//end namespace ChangarroDTO