///////////////////////////////////////////////////////////
//  CarritoDTO.cs
//  Implementation of the Class CarritoDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:41 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
	public class CarritoDTO {
        public int iIdProducto { get; set; }
        public int iIdCategoria { get; set; }
        public int iCantidad { get; set; }
        public int iCantidadExistente { get; set; }
        public decimal dPrecio { get; set; }
        public string cNombre { get; set; }
        public string cImagen { get; set; }
        public string cDescripcion { get; set; }

    }//end CarritoDTO

}//end namespace ChangarroDTO