///////////////////////////////////////////////////////////
//  CategoriasDTO.cs
//  Implementation of the Class CategoriasDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:43 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
	public class CategoriasDTO {

		public CategoriasDTO(){

		}

		~CategoriasDTO(){

		}

		public string cNombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

		public int iIdCategoria{
			get{
				return iIdCategoria;
			}
			set{
				iIdCategoria = value;
			}
		}

	}//end CategoriasDTO

}//end namespace ChangarroDTO