///////////////////////////////////////////////////////////
//  ClienteAdministradorDTO.cs
//  Implementation of the Class ClienteAdministradorDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:45 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
    public class ClienteAdministradorDTO {

        public ClienteAdministradorDTO(){

        }

        ~ClienteAdministradorDTO(){

        }
        /// <summary>
        /// Contiene el Apellido del cliente.
        /// </summary>
        public string cApellido { get; set; }
        /// <summary>
        /// Contiene el Correo del cliente.
        /// </summary>
        public string cCorreo { get; set; }
        /// <summary>
        /// Contiene el Nombre del cliente.
        /// </summary>
        public string cNombre { get; set; }
        /// <summary>
        /// Contiene el numero teléfonico del cliente.
        /// </summary>
        public string cTelefono { get; set; }
        /// <summary>
        /// Contiene la fecha de alta del cliente.
        /// </summary>
        public DateTime? dtFechaAlta { get; set; }
        /// <summary>
        /// Contiene la fecha de Baja del cliente.
        /// </summary>
        public DateTime? dtFechaBaja { get; set; }
        /// <summary>
        /// Contiene la fecha de Modificación del cliente.
        /// </summary>
        public DateTime? dtFechaModificacion { get; set; }
        /// <summary>
        /// Contiene el Identificador del Id.
        /// </summary>
        public int iIdCliente { get; set; }
        /// <summary>
        /// Contiene el Estatus del Cliente.
        /// </summary>
        public bool lEstatus { get; set; }
    }

}

//end ClienteAdministradorDTO

//end namespace ChangarroDTO