///////////////////////////////////////////////////////////
//  ClienteDTO.cs
//  Implementation of the Class ClienteDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:47:58 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
    public class ClienteDTO {
      

        public string cApellido { get; set; }

        public string cCorreo { get; set; }

        public string cNombre { get; set; }

        public string cTelefono { get; set; }

        public int iIdCliente { get; set; }

        public ClienteDTO(){

        }

        ~ClienteDTO(){

        }

    }//end ClienteDTO

}//end namespace ChangarroDTO