///////////////////////////////////////////////////////////
//  ClienteAdministradorDTO.cs
//  Implementation of the Class ClienteAdministradorDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:45 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
    public class ClienteAdministradorDTO {

        public ClienteAdministradorDTO(){

        }

        ~ClienteAdministradorDTO(){

        }

        public string cApellido { get; set; }

        public string cCorreo { get; set; }

        public string cNombre { get; set; }

        public string cTelefono { get; set; }

        public DateTime? dtFechaAlta { get; set; }

        public DateTime? dtFechaBaja { get; set; }

        public DateTime? dtFechaModificacion { get; set; }

        public int iIdCliente { get; set; }

        public bool lEstatus { get; set; }
    }

}

//end ClienteAdministradorDTO

//end namespace ChangarroDTO