///////////////////////////////////////////////////////////
//  ClienteDTO.cs
//  Implementation of the Class ClienteDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:47:58 p. m.
//  Original author: jose.gonzalez
///////////////////////////////////////////////////////////

namespace Changarro.Model.DTO
{
    public class ClienteDTO {
      
        /// <summary>
        /// Propiedad que almacena el correo del Cliente
        /// </summary>
        public string cCorreo { get; set; }

        /// <summary>
        /// Propiedad que almacena el nombre del Cliente
        /// </summary>
        public string cNombre { get; set; }

        /// <summary>
        /// Propiedad que almacena la imagen del cliente
        /// </summary>
        public string cImagen { get; set; }

        /// <summary>
        /// Propiedad que almacena el ID del cliente
        /// </summary>
        public int iIdCliente { get; set; }

        public ClienteDTO(){

        }

        ~ClienteDTO(){

        }

    }

}