///////////////////////////////////////////////////////////
//  DatosClienteDTO.cs
//  Implementation of the Class DatosClienteDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:47 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroDTO {
	public class DatosClienteDTO {

		public DatosClienteDTO(){

		}

		~DatosClienteDTO(){

		}

		public string cApellido{
			get{
				return cApellido;
			}
			set{
				cApellido = value;
			}
		}

		public string cCorreo{
			get{
				return cCorreo;
			}
			set{
				cCorreo = value;
			}
		}

		public string cNombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

		public string cTelefono{
			get{
				return cTelefono;
			}
			set{
				cTelefono = value;
			}
		}

	}//end DatosClienteDTO

}//end namespace ChangarroDTO