///////////////////////////////////////////////////////////
//  DireccionClienteDTO.cs
//  Implementation of the Class DireccionClienteDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:48 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

namespace Changarro.Model.DTO
{
    public class DomicilioDTO {

        public DomicilioDTO(){

        }

        ~DomicilioDTO(){

        }

        public int iIdDireccion { get; set; }

        public int iIdCliente { get; set; }

        public int iIdEstado { get; set; }

        public int iCodigoPostal { get; set; }

        public string cCalle { get; set; }        

        public string cColonia { get; set; }

        public string cDescripcion { get; set; }

        public string cMunicipio { get; set; }

        public string cNombre { get; set; }

        public string cNumeroExterior { get; set; }

        public string cNumeroInterior { get; set; }

        public string cEstado { get; set; }        

    }//end DireccionClienteDTO

}//end namespace ChangarroDTO