///////////////////////////////////////////////////////////
//  DireccionClienteDTO.cs
//  Implementation of the Class DireccionClienteDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:48 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

namespace Changarro.Model.DTO
{
    public class DomicilioDTO {

		public DomicilioDTO(){

		}

		~DomicilioDTO(){

		}

		public string cCalle{
			get{
				return cCalle;
			}
			set{
				cCalle = value;
			}
		}

		public string cCodigoPostal{
			get{
				return cCodigoPostal;
			}
			set{
				cCodigoPostal = value;
			}
		}

		public string cColonia{
			get{
				return cColonia;
			}
			set{
				cColonia = value;
			}
		}

		public string cDescripcion{
			get{
				return cDescripcion;
			}
			set{
				cDescripcion = value;
			}
		}

		public string cMunicipio{
			get{
				return cMunicipio;
			}
			set{
				cMunicipio = value;
			}
		}

		public string cNombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

		public string cNumeroExterior{
			get{
				return cNumeroExterior;
			}
			set{
				cNumeroExterior = value;
			}
		}

		public string cNumeroInterior{
			get{
				return cNumeroInterior;
			}
			set{
				cNumeroInterior = value;
			}
		}

		public int iIdDireccion{
			get{
				return iIdDireccion;
			}
			set{
				iIdDireccion = value;
			}
		}

		public int iIdEstado{
			get{
				return iIdEstado;
			}
			set{
				iIdEstado = value;
			}
		}

	}//end DireccionClienteDTO

}//end namespace ChangarroDTO