///////////////////////////////////////////////////////////
//  LoginDTO.cs
//  Implementation of the Class LoginDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:50 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
	public class LoginDTO {

		public LoginDTO(){

		}

		~LoginDTO(){

		}

		public string cContrasenia{
			get{
				return cContrasenia;
			}
			set{
				cContrasenia = value;
			}
		}

		public string cCorreo{
			get{
				return cCorreo;
			}
			set{
				cCorreo = value;
			}
		}

	}//end LoginDTO

}//end namespace ChangarroDTO