///////////////////////////////////////////////////////////
//  ProductosDTO.cs
//  Implementation of the Class ProductosDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:51 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
	public class ProductosDTO {

		public ProductosDTO(){

		}

		~ProductosDTO(){

		}

		public string cImagen{
			get{
				return cImagen;
			}
			set{
				cImagen = value;
			}
		}

		public string cNombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

		public decimal dPrecio{
			get{
				return dPrecio;
			}
			set{
				dPrecio = value;
			}
		}

		public int iIdProducto{
			get{
				return iIdProducto;
			}
			set{
				iIdProducto = value;
			}
		}

	}//end ProductosDTO

}//end namespace ChangarroDTO