///////////////////////////////////////////////////////////
//  RegistroDTO.cs
//  Implementation of the Class RegistroDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:52 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ChangarroDTO {
	public class RegistroDTO {

		public RegistroDTO(){

		}

		~RegistroDTO(){

		}

		public string cApellido{
			get{
				return cApellido;
			}
			set{
				cApellido = value;
			}
		}

		public string cContrasenia{
			get{
				return cContrasenia;
			}
			set{
				cContrasenia = value;
			}
		}

		public string cCorreo{
			get{
				return cCorreo;
			}
			set{
				cCorreo = value;
			}
		}

		public string cNombre{
			get{
				return cNombre;
			}
			set{
				cNombre = value;
			}
		}

	}//end RegistroDTO

}//end namespace ChangarroDTO