///////////////////////////////////////////////////////////
//  RegistroDTO.cs
//  Implementation of the Class RegistroDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:52 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

namespace Changarro.Model.DTO
{
    public class RegistroDTO {

        public RegistroDTO(){

        }

        ~RegistroDTO(){

        }

        /// <summary>
        /// Propiedad que almacena el apellido del usuario.
        /// </summary>
        public string cApellido { get; set; }

        /// <summary>
        /// Propiedad que almacena la contrase�a del usuario.
        /// </summary>
        public string cContrasenia { get; set; }

        /// <summary>
        /// Propiedad que almacena el correo del usuario.
        /// </summary>
        public string cCorreo { get; set; }

        /// <summary>
        /// Propiedad que almacena el Nombre del usuario.
        /// </summary>
        public string cNombre { get; set; }

    }//end RegistroDTO

}//end namespace ChangarroDTO