///////////////////////////////////////////////////////////
//  TarjetaDTO.cs
//  Implementation of the Class TarjetaDTO
//  Generated by Enterprise Architect
//  Created on:      20-nov.-2019 04:24:53 p. m.
//  Original author: Mike
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Changarro.Model.DTO {
	public class TarjetaDTO {

		public TarjetaDTO(){

		}

		~TarjetaDTO(){

		}

		public int iIdTarjeta { get; set; }

		public int iIdCliente { get; set; }
		public string cNombre { get; set; }

		public string cNumeroTarjeta { get; set; }

		public string cTitular { get; set; }

		public byte iAnioExpiracion { get; set; }

		public byte iMesExpiracion { get; set; }

	}//end TarjetaDTO

}//end namespace ChangarroDTO